### ISSUE TITLE
Compobility with mod : https://mods.factorio.com/mod/VehicleWagon2

### ISSUE THREAD

**Issue by Highlander37** [leehuk/factorio-tnfp#12]
Hello,
Looks like mod Tnfp didn't wok correctly work with mod : "VehicleWagon2"

If I loaded any car in to VehicleWagon then I saw message : 

"Request canceled: Train is no valid/exits."

A quick search for the cause of the problem, I showed me that this is due to the fact that with any changes in the composition of the train, his personal Id always changes.

But "VehicleWagon2" generate event, before loading into Wagon completed.

Could you create Compobility with this mod VehicleWagon2 on your mod side ?

**Comment by leehuk** [comment]
Potentially, I'll have a think but it's not an easy fix.  You're right as to the cause -- vehicle wagon is changing the train composition when it loads a car etc, which causes factorio to mark the original as invalid.

Offhand its likely to need another inter-mod API inside vehicle wagon to tell tnfp about the new train, which tnfp can then use to update its mappings cleanly.  No promises there though, I'll need to see what the other mod author thinks once there's something potentially usable

**Comment by leehuk** [comment]
Needs some testing and I need to chat with the Vehicle Wagon 2 author as there's some changes on that side, but seems ok

**Comment by Highlander37** [comment]
Wow!. Great news :)  
We are waiting for the full release of the mods

**Comment by leehuk** [comment]
Done and released as 0.12.4.  No changes to Vehicle Wagon 2 required, the mod author there pointed me towards a more generic API that does what we need.

If you have any problems feel free to open another issue -- I'm not sure how well it'll play with complicated train layouts with lots of vehicle wagons, but the simple case of a single wagon seems to be ok.
