### ISSUE TITLE
wishlist: collapse multiple stops with the same name to a single entry, or similar.

### ISSUE THREAD

**Issue by slippycheeze** [leehuk/factorio-tnfp#3]
Because I use LTN I have, like, a dozen stops named "depot" right now.  In the GUI selector they all show up as separate buttons, which isn't very useful.

It'd be nice to collapse them to a single name, or something, to make it easier to deal with.  The core schedule behaviour is to do just that, with a number on the right, and I think that is pretty reasonable.

**Comment by leehuk** [comment]
Ok, this is all now merged and released as part of v0.4.1 which I've pushed to the mod portal.  Anything further please don't hesitate to ask!
