### ISSUE TITLE
Mod not loading in multiplayer

### ISSUE THREAD

**Issue by DThomas44** [leehuk/factorio-tnfp#4]
Running headless 0.17.56
Mod version 0.4.1

Mod is in the mods folder, and shows in mod-list.json, but is not showing in the log or prompting for clients to sync mods.

First part of factorio-current.log:

> 0.000 2019-07-12 19:41:30; Factorio 0.17.56 (build 46133, linux64, headless)
> 0.039 Operating system: Linux (Ubuntu 19.04)
> 0.039 Program arguments: "/opt/factorio/bin/x64/factorio" "--start-server-load-latest" "--server-settings" "/opt/factorio/data/server-settings.json" "--use-server-whitelist" "--server-whitelist" "/opt/factorio/server-whitelist.json" 
> 0.039 Read data path: /opt/factorio/data
> 0.039 Write data path: /opt/factorio [2946/10735MB]
> 0.039 Binaries path: /opt/factorio/bin
> 0.047 System info: [CPU: Intel(R) Xeon(R) CPU           X5687  @ 3.60GHz, 8 cores, RAM: 5994 MB]
> 0.047 Environment: DISPLAY=<unset> WAYLAND_DISPLAY=<unset> DESKTOP_SESSION=<unset> XDG_SESSION_DESKTOP=<unset> XDG_CURRENT_DESKTOP=<unset> __GL_FSAA_MODE=<unset> __GL_LOG_MAX_ANISO=<unset> __GL_SYNC_TO_VBLANK=<unset> __GL_SORT_FBCONFIGS=<unset> __GL_YIELD=<unset>
> 0.047 Running in headless mode
> 0.052 Loading mod settings Bottleneck 0.10.4 (settings.lua)
> 0.052 Loading mod settings ElectricTrain 0.17.22 (settings.lua)
> 0.053 Loading mod core 0.0.0 (data.lua)
> 0.115 Loading mod base 0.17.56 (data.lua)
> 0.355 Loading mod Bottleneck 0.10.4 (data.lua)
> 0.473 Loading mod ElectricTrain 0.17.22 (data.lua)
> 0.592 Loading mod base 0.17.56 (data-updates.lua)
> 0.708 Loading mod ElectricTrain 0.17.22 (data-updates.lua)
> 0.828 Loading mod Squeak Through 1.3.0 (data-updates.lua)
> 0.953 Checksum for core: 2678823001
> 0.953 Checksum of base: 3299896472
> 0.953 Checksum of Bottleneck: 3138809866
> 0.953 Checksum of ElectricTrain: 3254112125
> 0.953 Checksum of Squeak Through: 3677677690
> 1.190 Info PlayerData.cpp:67: Local player-data.json available, timestamp 1562978424
> 1.190 Info PlayerData.cpp:74: Cloud player-data.json unavailable
> 1.192 Custom inputs active: 0
> 1.226 Factorio initialised

mod-list.json:

> {
>   "mods": 
>   [
>     
>     {
>       "name": "base",
>       "enabled": true
>     },
>     
>     {
>       "name": "Bottleneck",
>       "enabled": true
>     },
>     
>     {
>       "name": "ElectricTrain",
>       "enabled": true
>     },
>     
>     {
>       "name": "Squeak Through",
>       "enabled": true
>     },
>     
>     {
>       "name": "TrainNetworkForPlayers",
>       "enabled": true
>     }
>   ]
> }

_Also attempted to load server with this mod as only mod, still does not load._

**Comment by leehuk** [comment]
You'll need the factorio stdlib mod as well, at version 1.0.4 or above:
https://mods.factorio.com/mod/stdlib/downloads

**Comment by DThomas44** [comment]
That got it working, thank you.
