### ISSUE TITLE
Doesn't work with the LTN stop anymore

### ISSUE THREAD

**Issue by nahfe** [leehuk/factorio-tnfp#8]

**Comment by leehuk** [comment]
Could you provide some detail please?  What is it you're trying to do and what isn't working?

Also factorio version and the version of the LTN and TNfP mods please.

**Comment by leehuk** [comment]
Ah, I ran some testing and ltn stops are falling through to the default behaviour when they're not depots, rather than being marked as safe.  Its fixed in c1ea401 so once some other fixes are done I'll do a release

**Comment by leehuk** [comment]
This should now be fixed in 0.9.4
