### ISSUE TITLE
"On Arrival" not working as expected

### ISSUE THREAD

**Issue by tailkinker** [leehuk/factorio-tnfp#9]
When I set the "On Arrival" option in the TNfP Station Select dialog to "Manual Mode", the train does not switch to manual mode on arrival, and the selector returns to "Default."

**Comment by leehuk** [comment]
I've released v0.10.6 which should fix it, at least seems ok against 0.18.30 now -- looks like it was storing something as state info it probably shouldn't have been.

Cheers, Lee H
